export const dummyUsers = [
  {
    id: '1',
    firstname: 'Andi',
    lastname: 'Saputra',
    email: 'andi.saputra@example.com',
    role: 'admin',
    created_at: '2024-11-20T10:00:00Z',
  },
  {
    id: '2',
    firstname: 'Budi',
    lastname: 'Santoso',
    email: 'budi.santoso@example.com',
    role: 'user',
    created_at: '2024-12-01T09:30:00Z',
  },
  {
    id: '3',
    firstname: 'Citra',
    lastname: 'Lestari',
    email: 'citra.lestari@example.com',
    role: 'manager',
    created_at: '2025-01-15T14:20:00Z',
  },
  {
    id: '4',
    firstname: 'Dewi',
    lastname: 'Kartika',
    email: 'dewi.kartika@example.com',
    role: 'user',
    created_at: '2025-03-10T08:45:00Z',
  },
  {
    id: '5',
    firstname: 'Eko',
    lastname: 'Prasetyo',
    email: 'eko.prasetyo@example.com',
    role: 'admin',
    created_at: '2025-04-05T16:10:00Z',
  },
  {
    id: '6',
    firstname: 'Fajar',
    lastname: 'Hidayat',
    email: 'fajar.hidayat@example.com',
    role: 'editor',
    created_at: '2025-04-10T12:00:00Z',
  },
  {
    id: '7',
    firstname: 'Gita',
    lastname: 'Nugraha',
    email: 'gita.nugraha@example.com',
    role: 'user',
    created_at: '2025-04-12T13:15:00Z',
  },
  {
    id: '8',
    firstname: 'Hari',
    lastname: 'Kusuma',
    email: 'hari.kusuma@example.com',
    role: 'manager',
    created_at: '2025-04-14T10:30:00Z',
  },
  {
    id: '9',
    firstname: 'Intan',
    lastname: 'Permata',
    email: 'intan.permata@example.com',
    role: 'admin',
    created_at: '2025-04-15T08:00:00Z',
  },
  {
    id: '10',
    firstname: 'Joko',
    lastname: 'Susilo',
    email: 'joko.susilo@example.com',
    role: 'user',
    created_at: '2025-04-16T09:20:00Z',
  },
  {
    id: '11',
    firstname: 'Kiki',
    lastname: 'Andayani',
    email: 'kiki.andayani@example.com',
    role: 'editor',
    created_at: '2025-04-17T11:45:00Z',
  },
  {
    id: '12',
    firstname: 'Lina',
    lastname: 'Wijaya',
    email: 'lina.wijaya@example.com',
    role: 'user',
    created_at: '2025-04-18T14:00:00Z',
  },
  {
    id: '13',
    firstname: 'Miko',
    lastname: 'Setiawan',
    email: 'miko.setiawan@example.com',
    role: 'admin',
    created_at: '2025-04-19T07:10:00Z',
  },
  {
    id: '14',
    firstname: 'Nina',
    lastname: 'Ramadhani',
    email: 'nina.ramadhani@example.com',
    role: 'user',
    created_at: '2025-04-20T16:00:00Z',
  },
  {
    id: '15',
    firstname: 'Oscar',
    lastname: 'Gunawan',
    email: 'oscar.gunawan@example.com',
    role: 'manager',
    created_at: '2025-04-21T08:20:00Z',
  },
  {
    id: '16',
    firstname: 'Putri',
    lastname: 'Mahardika',
    email: 'putri.mahardika@example.com',
    role: 'editor',
    created_at: '2025-04-22T09:30:00Z',
  },
  {
    id: '17',
    firstname: 'Qori',
    lastname: 'Fadilah',
    email: 'qori.fadilah@example.com',
    role: 'user',
    created_at: '2025-04-23T10:40:00Z',
  },
  {
    id: '18',
    firstname: 'Rafi',
    lastname: 'Pradana',
    email: 'rafi.pradana@example.com',
    role: 'admin',
    created_at: '2025-04-24T11:50:00Z',
  },
  {
    id: '19',
    firstname: 'Sinta',
    lastname: 'Nuraini',
    email: 'sinta.nuraini@example.com',
    role: 'user',
    created_at: '2025-04-25T12:00:00Z',
  },
  {
    id: '20',
    firstname: 'Taufik',
    lastname: 'Halim',
    email: 'taufik.halim@example.com',
    role: 'editor',
    created_at: '2025-04-26T13:10:00Z',
  },
];
